---
- name: install prerequisites
  sudo: true
  apt: name={{ item }} state=latest
  with_items:
    - libpq-dev
    - python-psycopg2

- name: Install postgres
  apt: name=postgresql=9.3+154 state=present
  sudo: yes

- name: Install postgres-contrib
  apt: name=postgresql-contrib=9.3+154 state=present
  sudo: yes

