---
- name: Install nginx
  apt: name=nginx=1.4.6-1ubuntu3.3 state=present
  sudo: yes

- name: Copy nginx.conf file
  template: src=default.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx
  sudo: yes
